import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Conos y Waffles Clarita</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar></Navbar>
      </main>

      <footer className={styles.footer}>
        <a
          href="google.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <h3 className={styles.webapp}>WebApp</h3>
        </a>
      </footer>
    </div>
  )
}
